initial version
frantizek/PuntoDeVentaDinastia pull request #5
Opened 2023-05-16 16:01 UTC by frantizek

2023-05-17 04:59 UTC, cibervicho requested changes

2023-05-17 04:59 UTC, cibervicho commented on README.md
> +# PuntoDeVentaDinastia
Me gustaria ver un poco mas de informacion sobre el proyecto para asi tener un poco mas de contexto de lo que se va a revisar.
Tambien estaria muy bien agregar informacion de como setear el ambiente para poder ejectuar el codigo que se va desarrollando.
Veo que usas tkinter, lo cual es genial para hacer aplicaciones graficas, pero no se como instalarlo o que paquetes se necesitan, por lo que te aconsejo pongas un requirements.txt con los paquetes y modulos que se necesitan instalar para poder ejecutar el proyecto.

2023-06-01 17:27 UTC, closed without merging

2023-06-01 17:27 UTC, frantizek commented
closing this PR

2023-06-01 18:24 UTC, cibervicho commented
Como que no se tomó en cuenta mi revisión... 😣